root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/hitechcloud_keygate_licensing ./cmd/server"
  entrypoint = "./tmp/hitechcloud_keygate_licensing"
  include_ext = ["go"]
  exclude_dir = ["tmp", "bin", "web", "node_modules", "vendor"]
  delay = 500

[misc]
  clean_on_exit = true
